// <auto-generated />
using System;
using Financas.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financas.Api.Migrations
{
    [DbContext(typeof(FinancasDbContext))]
    [Migration("20260423024304_AddCartaoEFAndFaturaConfigurations")]
    partial class AddCartaoEFAndFaturaConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Financas.Api.Entities.CartaoCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DiaFechamento")
                        .HasColumnType("int")
                        .HasColumnName("dia_fechamento");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("int")
                        .HasColumnName("dia_vencimento");

                    b.Property<decimal>("Limite")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("limite_cartao_credito");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome_cartao_credito");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status_cartao_credito");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("cartao_credito", (string)null);
                });

            modelBuilder.Entity("Financas.Api.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Icone")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("icone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("Financas.Api.Entities.ContaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome_conta_bancaria");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo_conta_bancaria");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tipo_conta_bancaria");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("contas_bancarias", (string)null);
                });

            modelBuilder.Entity("Financas.Api.Entities.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CartaoCreditoId")
                        .HasColumnType("int")
                        .HasColumnName("cartao_credito_id");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_fechamento");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_vencimento");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status_fatura");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_pago");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("CartaoCreditoId");

                    b.HasIndex("CartaoCreditoId", "DataInicio", "DataFechamento");

                    b.ToTable("faturas", (string)null);
                });

            modelBuilder.Entity("Financas.Api.Entities.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CartaoCreditoId")
                        .HasColumnType("int")
                        .HasColumnName("cartao_credito_id");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    b.Property<int?>("ContaBancariaId")
                        .HasColumnType("int")
                        .HasColumnName("conta_bancaria_id");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_lancamento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao");

                    b.Property<int?>("FaturaId")
                        .HasColumnType("int")
                        .HasColumnName("fatura_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("CartaoCreditoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaBancariaId");

                    b.HasIndex("FaturaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("lancamentos", (string)null);
                });

            modelBuilder.Entity("Financas.Api.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmado");

                    b.Property<string>("EmailPendente")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email_pendente");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("TokenConfirmacao")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token_confirmacao");

                    b.Property<DateTime?>("TokenExpiracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("token_expiracao");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Financas.Api.Entities.CartaoCredito", b =>
                {
                    b.HasOne("Financas.Api.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Financas.Api.Entities.Categoria", b =>
                {
                    b.HasOne("Financas.Api.Entities.Usuario", "Usuario")
                        .WithMany("Categorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Financas.Api.Entities.ContaBancaria", b =>
                {
                    b.HasOne("Financas.Api.Entities.Usuario", "Usuario")
                        .WithMany("ContasBancarias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Financas.Api.Entities.Fatura", b =>
                {
                    b.HasOne("Financas.Api.Entities.CartaoCredito", "CartaoCredito")
                        .WithMany("Faturas")
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CartaoCredito");
                });

            modelBuilder.Entity("Financas.Api.Entities.Lancamento", b =>
                {
                    b.HasOne("Financas.Api.Entities.CartaoCredito", "CartaoCredito")
                        .WithMany("Lancamentos")
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Financas.Api.Entities.Categoria", "Categoria")
                        .WithMany("Lancamentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Financas.Api.Entities.ContaBancaria", "ContaBancaria")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Financas.Api.Entities.Fatura", "Fatura")
                        .WithMany("Lancamentos")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Financas.Api.Entities.Usuario", "Usuario")
                        .WithMany("Lancamentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CartaoCredito");

                    b.Navigation("Categoria");

                    b.Navigation("ContaBancaria");

                    b.Navigation("Fatura");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Financas.Api.Entities.CartaoCredito", b =>
                {
                    b.Navigation("Faturas");

                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("Financas.Api.Entities.Categoria", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("Financas.Api.Entities.ContaBancaria", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("Financas.Api.Entities.Fatura", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("Financas.Api.Entities.Usuario", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("ContasBancarias");

                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
